version: '{build}'
image: Visual Studio 2017
configuration: Release

before_build:
  - nuget restore
build:
  verbosity: minimal

test_script:
 - '%xunit20%\xunit.console RangedObservableCollection.Tests\bin\Debug\netcoreapp2.0\RangedObservableCollection.Tests.dll -appveyor'

nuget:
  disable_publish_on_pr: true
artifacts:
- path: RangedObservableCollection\bin\$(CONFIGURATION)\
- path: RangedObservableCollection\bin\$(CONFIGURATION)\*.nupkg
